server:
  port: 8081

spring:
  application:
    name: service-authentification
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        register: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: guest
    password: guest
    exchange: utilisateur.nouveau
    queue: utilisateur.nouveau
    routingkey: utilisateur.nouveau